export const NEXT_REVALIDATE_TOPICS_AFTER = 86400;

export enum ErrorCodes {
  RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED",
  BAD_REQUEST = "BAD_REQUEST",
  ARTICLE_TOO_LENGHTY = "ARTICLE_TOO_LENGHTY",
}
